# Generated by Django 3.1.5 on 2021-01-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210106_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='tag',
            field=models.CharField(default='cricket', max_length=200),
            preserve_default=False,
        ),
    ]
