# Generated by Django 3.1.5 on 2021-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_videos_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='published',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.CharField(default='aaaa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.CharField(default='aaaa', max_length=200),
            preserve_default=False,
        ),
    ]
